# Generated by Django 6.1.1 on 2026-09-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('organizations', '0002_alter_organization_id_alter_organizationsettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('recording_url', models.CharField(blank=True, max_length=500)),
                ('transcript', models.TextField(blank=True, help_text='Full text conversation')),
                ('summary', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=50)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='campaigns.outboundcampaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
