# Generated by Django 5.1.1 on 2026-09-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_calllog_ai_agent_calllog_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of tags generated by AI (e.g. ['Sales', 'Complaint'])"),
        ),
    ]
