# Generated by Django 5.1.1 on 2026-09-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='document_file',
            field=models.FileField(blank=True, help_text='Or upload a PDF/TXT file directly', null=True, upload_to='knowledge_docs/'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='file_url',
            field=models.URLField(blank=True, help_text='External URL (e.g., Notion public link)', max_length=1000, null=True),
        ),
    ]
