# Generated by Django 4.2.30 on 2026-09-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_groups',
            field=models.ManyToManyField(blank=True, help_text='The custom agent groups this user belongs to within the organization.', related_name='agents', to='agents.agentgroup'),
        ),
    ]
