# Generated by Django 5.1.1 on 2026-09-10 00:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organization_id_alter_organizationsettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='v1', help_text='API Version e.g., v1', max_length=10)),
                ('name', models.CharField(help_text="Unique name for the AI to call. e.g., 'check_order_status'", max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'Only alphanumeric characters and underscores are allowed.')])),
                ('description', models.TextField(help_text='Instructions for the AI on WHEN to use this action.')),
                ('protocol', models.CharField(choices=[('HTTP', 'HTTP (REST)'), ('GRAPHQL', 'GraphQL'), ('WEBSOCKET', 'WebSocket'), ('GRPC', 'gRPC')], default='HTTP', max_length=20)),
                ('endpoint_url', models.CharField(help_text='e.g., https://api.example.com/v1/users/{{user_id}}', max_length=1000)),
                ('http_method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='POST', max_length=10, null=True)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='{"Authorization": "Bearer token"}')),
                ('body_template', models.TextField(blank=True, help_text='JSON or GraphQL template with {{variables}}')),
                ('input_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema defining the exact parameters the AI needs to ask the user for.')),
                ('response_extractor', models.CharField(blank=True, help_text="JSONPath to extract data. e.g. '$.data.status'", max_length=255, null=True)),
                ('timeout_seconds', models.IntegerField(default=10)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
