# Generated by Django 4.2.30 on 2026-09-09 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(help_text='Instructions defining the AI persona and constraints.')),
                ('gemini_voice', models.CharField(choices=[('Aoede', 'Aoede (Female, smooth)'), ('Charon', 'Charon (Male, deep)'), ('Fenrir', 'Fenrir (Male, energetic)'), ('Kore', 'Kore (Female, clear)'), ('Puck', 'Puck (Male, friendly)')], default='Aoede', max_length=50)),
                ('language', models.CharField(choices=[('ar-EG', 'Arabic (Egypt)'), ('ar-SA', 'Arabic (Saudi Arabia)'), ('ar-AE', 'Arabic (UAE)'), ('ar-KW', 'Arabic (Kuwait)'), ('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('es-ES', 'Spanish (Spain)'), ('fr-FR', 'French (France)'), ('de-DE', 'German (Germany)')], default='ar-EG', max_length=20)),
                ('temperature', models.FloatField(default=0.7, help_text='Values from 0.0 (Strict) to 1.0 (Creative)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
