# Generated by Django 4.2.30 on 2026-09-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_aiagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentgroup',
            name='ai_agent',
            field=models.ForeignKey(blank=True, help_text="Select the AI persona. Only required if Group Type is 'AI'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_groups', to='agents.aiagent'),
        ),
        migrations.AddField(
            model_name='agentgroup',
            name='group_type',
            field=models.CharField(choices=[('HUMAN', 'Human Agents'), ('AI', 'AI Agent (Automated)')], default='HUMAN', max_length=10),
        ),
    ]
