# Generated by Django 5.1.1 on 2026-09-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions_engine', '0001_initial'),
        ('agents', '0004_alter_agentgroup_id_alter_aiagent_id_agentprofile'),
        ('knowledge_base', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='actions',
            field=models.ManyToManyField(blank=True, help_text='Select specific dynamic actions this AI agent is allowed to execute.', related_name='ai_agents', to='actions_engine.actiondefinition'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='knowledge_documents',
            field=models.ManyToManyField(blank=True, help_text='Select specific knowledge base documents this AI agent is allowed to search.', related_name='ai_agents', to='knowledge_base.knowledgedocument'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='workflows',
            field=models.ManyToManyField(blank=True, help_text='Select n8n workflows attached to this agent (Pre/Mid/Post call).', related_name='ai_agents', to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='agentgroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
