# Generated by Django 5.1.1 on 2026-09-10 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0003_calllog_tags'),
        ('organizations', '0003_alter_organization_id_alter_organizationsettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('AI_MINUTES', 'AI Minutes'), ('SIP_MINUTES', 'SIP / PSTN Minutes'), ('STORAGE_MB', 'Storage (MB)'), ('RAG_QUERIES', 'RAG / Knowledge Queries'), ('WORKFLOW_EXECUTIONS', 'Workflow Executions (n8n)')], db_index=True, max_length=30)),
                ('amount', models.FloatField(help_text='Unit depends on usage_type (seconds, MB, count …)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='analytics.calllog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
