# Generated by Django 4.2.30 on 2026-09-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIPTrunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Twilio Primary, Local PBX', max_length=100)),
                ('provider', models.CharField(blank=True, help_text='e.g., Twilio, Vonage', max_length=100, null=True)),
                ('host', models.CharField(help_text='SIP URI or IP Address', max_length=255)),
                ('port', models.IntegerField(default=5060)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='sip_trunk',
            field=models.ForeignKey(blank=True, help_text='The SIP Trunk this number belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='telephony.siptrunk'),
        ),
    ]
