# Generated by Django 5.1.1 on 2026-09-10 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organization_id_alter_organizationsettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='Used by AI if MID_CALL to understand when to trigger.')),
                ('trigger_type', models.CharField(choices=[('PRE_CALL', 'Pre-Call (Context Fetch)'), ('MID_CALL', 'Mid-Call (AI Tool/Action)'), ('POST_CALL', 'Post-Call (Wrap-up)')], default='POST_CALL', max_length=20)),
                ('n8n_workflow_id', models.CharField(blank=True, help_text='ID of the workflow in n8n', max_length=255, null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='The n8n webhook URL to trigger this workflow', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., My Telegram Bot', max_length=150)),
                ('credential_type', models.CharField(help_text='n8n credential type e.g., telegramApi', max_length=100)),
                ('n8n_credential_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
